### ISSUE TITLE
RGP drawn in spot figure is incorrect 

### ISSUE THREAD

**Issue by Quentinfdg** [labgem/PPanGGOLiN#124]
Hello, I have a small problem with RGPs and spots. 
In my data I have 2 RGPs, NZ_CP061647.1_RGP_0  from 3015 to 57479 bp and NZ_CP061647.1_RGP_1 from 67376 to 88466 bp (see figure below).
![plastic_regions](https://github.com/labgem/PPanGGOLiN/assets/123958629/7bae3cd1-29ad-4238-89f1-ab889bbae9e4)
Both RGP are inside a spot, the spot 36 for NZ_CP061647.1_RGP_1 and spot 63 for NZ_CP061647.1_RGP_0. (see figures below).
![spots_36](https://github.com/labgem/PPanGGOLiN/assets/123958629/c6075f8b-e344-4a4b-b791-9bae52f953c7)
![spots_63](https://github.com/labgem/PPanGGOLiN/assets/123958629/3fe57310-2ecd-43ef-a93c-d1bbf0c471c5)
But when I look at the figure of spot 36 for  GCF_014722015.1_ASM1472201v1 the RGP drawn is NZ_CP061647.1_RGP_0 instead of NZ_CP061647.1_RGP_1 (I put the position of the gene families of the content) 
![spot_36_figure](https://github.com/labgem/PPanGGOLiN/assets/123958629/9df276eb-fde5-47c4-b6d4-d9ab8763eabe)

**Comment by axbazin** [comment]
Hi,

Looks like a bug indeed.
Can you share the .h5 file ? It will be easier to find with data to replicate it.

Adelme

**Comment by axbazin** [comment]
Hi,

Indeed a bug, and a pretty nasty one.

After some explorations, I found what happened. It can happen specifically it this very special case that you have, where you have a circular contig, with persistent genes on it, the RGP actually ends right on the contig "end", but since it's circular, the border is actually at the "beginning" of the contig. 

When checking out which positions to draw, PPanGGOLiN actually inverted the "start" and the "stop" genes to draw from, and drew what was in-between the two "border" genes, but not on the proper "side" (not sure if the sentence is clear here...), so in this case the other RGP with some additional persistent genes that are not belonging to either RGPs, making it look like both RGPs were inverted.

Fix won't happen tonight, I'll have to think through on how to do this in a smarter way.

Adelme
