### ISSUE TITLE
Getting MSAs for single-copy gene families when duplicates are tolerated

### ISSUE THREAD

**Issue by szhan** [labgem/PPanGGOLiN#223]
I'm looking at the code for writing FastA files for computing MSAs [here](https://github.com/labgem/PPanGGOLiN/blob/f3ba6a1f33256f19175b570c4b711bb8970d0365/ppanggolin/formats/writeMSA.py#L123). I'm trying to understand what happens to the multi-copy members of a genome in single-copy families defined when multiple copies are tolerated. Looking at the code, it seems like such multi-copy members are not printed to FastA at all; so, they appear to be lost if only looking at the output FastA file. Could you please confirm this? Sorry if I misunderstand something. I appreciate that it could get tricky to try to figure out whether the multi-copy members are fragments of the same gene. Thank you.

**Comment by szhan** [comment]
Thanks, Adelme.

A related matter. I noticed that the parameter description for `dup_margin`[here](https://github.com/labgem/PPanGGOLiN/blob/f3ba6a1f33256f19175b570c4b711bb8970d0365/ppanggolin/formats/writeMSA.py#L25) doesn't seem quite right.

I think that it should be the same as the parameter description [here](https://github.com/labgem/PPanGGOLiN/blob/f3ba6a1f33256f19175b570c4b711bb8970d0365/ppanggolin/geneFamily.py#L427).

Also, isn't a default value of `0.95` for `dup_margin`a bit high for determining if a gene family is single-copy or not?

**Comment by axbazin** [comment]
Indeed, for the description. And actually the 2nd function that you pointed should probably be used instead of the code in use currently in writeMSA.

And indeed the default value is way off but thankfully it should never be used and the command line default, at a much more adapted value of `0.05` seems to be in use in all of the function calls.

Both of those do deserve a fix, thank you for reporting this.
