### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by camilae86** [labgem/PPanGGOLiN#276]
Hi!
I have this error during clustering (ppanggolin cluster -p pangenome.h5):

raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createdb', '/tmp/tmp84p8ohw5/nucleotid_sequences', '/tmp/tmp84p8ohw5/nucleotid_sequences_db']' returned non-zero exit status 1.

**Comment by axbazin** [comment]
Hi!

With which version of ppanggolin did you get this error?

Last time I saw this error, it was related to a full disk in the "/tmp" folder. This can happen if your pangenome is pretty big (multiple thousands of genomes) and/or if the "/tmp" disk space is very small (a few Gb).

If your problem is neither, could you share the complete log, and eventually the input that you used if that is possible for you?

I hope this helps!
Adelme

**Comment by axbazin** [comment]
Hi,

So, this is likely related to an unexpected formatting of one of your gff3 file (likely R_18628.gff). 

If you wish you can add it to the issue and I can take a look, but overall we try to follow the specifications indicated here: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

I see that there are warnings about contig length being unknown, so maybe it's related to the contig feature (or lack of thereof) in your gff3 file? 
Though, without an example I can only guess.

Adelme

**Comment by axbazin** [comment]
Hi,

I hope you managed to find a solution to your problem.
Closing for now. If this issue is still a thing feel free to re-open it.

Adelme
