### ISSUE TITLE
Using chromosome or the complete assembly in panrgp

### ISSUE THREAD

**Issue by genomesandMGEs** [labgem/PPanGGOLiN#37]
Hey guys,

I have several complete bacterial assemblies to use as input for panrgp. Does it make a difference to use the assembly (chromosome + any eventual plasmid), or the chromosome alone?
Thanks!

**Comment by axbazin** [comment]
Hello,

The only difference between the two solutions is that your plasmids will probably be predicted as RGP, since they are usually not conserved among all of the genomes of a given species.

You can use chromosome + any eventual plasmid without any problem

If you have any other question or run into problems please do not hesitate :)
