### ISSUE TITLE
Install without Conda

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#74]
Hello,

I'm trying to use PPanGGOLiN and ask my IT service to install it on our grid, but they answered me we don't use Conda on our system. So, my question is, is there another possibility to install PPanGGOLiN, and if yes, where can I find the documentation for it, please?
Thank you very much

Have a nice day
Cheers
C.

**Comment by jpjarnoux** [comment]
Hi,

It's possible to install PPanGGOLiN without use Conda, but it's easier. That's why it's not describe, we will think about create alternative to conda. Thanks for your report. 

The second easiest way is to get the docker image like this :
```
docker pull quay.io/biocontainers/ppanggolin:1.2.74--py38hbff2b2d_0  # or quay.io/biocontainers/ppanggolin:x.x.x-py3x for another version
```

The last way is an install step by step with pip:
1. install software dependencies
    - [Prodigal](https://github.com/hyattpd/Prodigal)
    - [Aragorn](http://www.ansikte.se/ARAGORN/Downloads/)
    - [Infernal](https://github.com/EddyRivasLab/infernal) 
    - [MMSeqs2](https://github.com/soedinglab/MMseqs2)
    - [MAFFT](https://mafft.cbrc.jp/alignment/software/)

> Note : Be sure that all the install are working and in your path

2. install python dependencies,
    - Download this file [requirements_pip.txt](https://github.com/labgem/PPanGGOLiN/files/8168778/requirements_pip.txt)
    - Clone PPanGGOLiN repository
    - install requirements

You can copy and past the following line :

```
git clone https://github.com/labgem/PPanGGOLiN.git
cd PPanGGOLiN
wget https://github.com/labgem/PPanGGOLiN/files/8168778/requirements_pip.txt
pip install -r requirements_pip.txt  # you possibly need to had --user option if it's not work
```
> Note : Be sure to use a python version compatible with PPanGGOLiN (3.6 to 3.8)

3. Install PPanGGOLiN
`pip install .  # you need to be in the PPanGGOLiN directory as above-mentioned`

4. test install 
You can test the installation as such : 
```
cd testingDataset
ppanggolin --version
ppanggolin all --fasta organisms.fasta.list --output mybasicpangenome   # if you want multiprocessing add --cpu 8 (for 8 cpu)
ppanggolin info --pangenome mybasicpangenome/pangenome.h5 --content --parameters --status
```  
I test the both ways, and they're working on my computer. I hope it'll help !

Don't hesitate if you've encounter problems to install, or after by using PPanGGOLiN

**Comment by cmonat** [comment]
Thanks, I'll try these.

**Comment by jpjarnoux** [comment]
Hello,
Have you tried it? Did it work? Did you encounter any problems?
Thank you for your feedback.
