### ISSUE TITLE
User-Defined Filtering and Annotation 

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#78]
Hello!  

I am not sure if I have missed something in the wiki or this is possible in some way I haven't quite figured out, so I am reaching out to see if you can point me in the correct direction.  I have a pangenome graph that I am viewing in Gephi that I would love to be able to take a defined subset of ORF from the underlying collection (e.g. found enriched in a specific niche) and ask the question "which nodes on the pangenome image do these ORF fall into, and are those nodes forming syntenic blocks across the pangenome?" Further, it would be incredibly advantageous to be able to do this en-masse with collections of genes (user-defined subsets of ORF) and create something like a 'user defined' partition (that can be handled in the same way as ppanggolin-defined partitions (highlight all on Gephi image, color change, etc.).

Thanks!

**Comment by jpjarnoux** [comment]
Hi,
I never try, but maybe is possible. I will search information and come back to you ASAP.
Thanks

**Comment by ggautreau** [comment]
Hi @seajane,

Using Gephi, you can filter the nodes based on a particular query https://www.youtube.com/watch?v=0R86bJVxMrA

So you can filter gene families belonging to some specific genomes. Just make sure to use the full gexf file `pangenomeGraph.gexf` with the genome information and not the lighter one. You can then filter persistent families to visualize variable synteny blocs (from shell and cloud families).

But indeed, RGP, spots and panModules are not exported in the GEXF file, it could be an enhancement to add them in this output file in order to improve the exploration of the graph.

Moreover, we are working on an ad hoc visualization interface dedicated to the exploration of pangenome graph but it is a huge work, still in progress.

Best regards.

**Comment by seajane** [comment]
@ggautreau Thank you so much for looking into this and I appreciate the link to the Gephi tutorial.  I look forward to seeing the new updates, they sound very exciting!
