### ISSUE TITLE
Not sure how to use genomic context option

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#88]
Hello,

I'm confused because of the following sentence in the documentation part Genomic context:

>From version 1.2.45, it is possible to search genomic context in a pangenome graph using PPanGGOLiN. A genomic context corresponds to a group of genes/proteins with a functional interest, often found together in the genomes. They are detected by extracting a subgraph obtained by filtering edges connecting the sequences of interest in the pangenome.

If I understand correctly, it is possible to identify common genomic context between groups of prot with a specific interest. For that, I should provide the soft, theses sequences of interest.

I have made a try, by aligning some protein that I extracted from the NCBI to my pangenome (composed of 50 genomes) but it doesn't find any gene contexts. I have tried also to align some proteins that I know to be present inside my pangenome, but the results are the same: no gene contexts were found. 

Did I misunderstand the purpose of this analysis, or did I miss something to make it work?
Thank you in advance

Have a great day
C.

**Comment by axbazin** [comment]
Hi,

@jpjarnoux will likely be more helpful than me on this one but he's away this week. I have not used this method a lot myself.

I think you have understood correctly the purpose of this method. Just in case, phrased differently, the idea is that, given a group of protein sequences, you try to find whether they are colocalized or not in the pangenome, so in other words if they are found generally close together among the genomes or not.

You should get an output file 'gene_context.tsv' in any case, whether the proteins are found or not, and whether they are close to each other or not. If they are indeed close to each other, they should have the same identifier in the first column of 'gene_context.tsv'. If they are found within the pangenome but not close to each other, they will have a different value in the first column, and the second column should be filled. If they are not in the pangenome, I think the behavior is that the 2nd column is filled with NA, but I'm not sure.

Does this answer you question ?

If not, maybe providing the log, or eventually the 'gene_context.tsv' file, will help me giving a more accurate answer.

Have a great day,
Adelme

**Comment by axbazin** [comment]
Indeed, I'm afraid we will have to wait for Jérôme to return and answer this issue I do not know this module well enough, sorry.

Do you have 6 sequences in your prot_from_ncbi.fasta ?
And 6 lines in sequences_partition_projection.tsv ?

**Comment by cmonat** [comment]
Ok, thanks :)

In the sequences_partition_projection.tsv I only have one line and there were 10 sequences in the prot_from_ncbi.fasta file ... =S

**Comment by jpjarnoux** [comment]
Hi !

Sorry, I've been very busy the last few weeks. I looked at your problem and on my test dataset and got a gene_context.tsv file.
Maybe the issue is with using the default parameters. Could you try increasing the transitive parameter and decreasing the Jaccard similarity threshold?
Run with the debug mode `--verbose 2`. Finally, your command will look at something like that :
`ppanggolin context -p pangenome.h5 --sequence my_seq.fasta -o out_directory --transitive 10 --jaccard 0.5 --verbose 2`

If you find any context, we could speak more about the parameters.

**Comment by jpjarnoux** [comment]
What I understand is that PPanGGOLiN find corresponding gene families to your input sequences. Nevertheless, in the pangenome, a context is not find. Is it possible for genes to be more than 10 genes apart in genomes? Because I think that the problem comes more from the parameters used than from a bug in the code.
In any case, I will work on the code to make it more explicit and to understand what is going on. In the meantime, we should increase the transitivity to see if we don't end up detecting something.

**Comment by cmonat** [comment]
Ok, thank you very much for your help.
I'll make some tests increasing the transitivity, thanks

Have a great day
C.
