### ISSUE TITLE
Position column in pangenomeGraph.json file

### ISSUE THREAD

**Issue by mkesapra** [labgem/PPanGGOLiN#93]
Hello!

As explained in your wiki, the projection folder has tsv files for each genome consisting of information as in: 
![Screen Shot 2022-08-16 at 11 01 41 PM](https://user-images.githubusercontent.com/89179388/185045822-23790aa2-ab28-4649-9bca-94532759c3aa.png)

In the pangenomeGraph.json file, I see along with the above information for each genome there is also a column called **position**:
![json](https://user-images.githubusercontent.com/89179388/185048463-d189a6f2-f97e-4a98-af1b-a93f50e85b97.png)

Could you please explain what does this column **position** indicate? Also is there any reason why this column is not included in the projections folder tsv files?

We are trying to work with encoding the gene position, so was wondering if this is what we are looking for.

Thank you!

**Comment by axbazin** [comment]
Hi,

The position column indicates the order in which the genes were read on that contig, starting from 0. 
It is not in the projection .tsv file explicitely because it is implicitely indicated by the order in which the genes are written in that file (so first line of a .tsv projection file should correspond to gene at position 0 for that contig, second line to position 1, ...). It should also correspond to the order of the genes if you order them by their start position, if I'm not mistaken.

So it sounds to me like it is what you are looking for !

Adelme

**Comment by mkesapra** [comment]
Hi Adelme, 

Thank you. 

In this example, the position says 38, but in the projection tsv file it is arranged in the row 4136 close to the number ending with CDS_4141. 
![json](https://user-images.githubusercontent.com/89179388/185200878-dd674882-c95c-4860-aa9a-6a79dad7c84d.png)
 
Am I missing something here? If I had to refer as per the order of the genes in the tsv file it would indicate a wrong position.

**Comment by axbazin** [comment]
Hi,
It should be the gene at position 38 of the LCUS01000006.1 contig. It appears at row 4136, but it should be the 39th CDS row of the contig with id LCUS01000006.1, if everything is working as expected.

The number after the CDS in the identifier is incremental at the genome scope, which is why it should generally be either the same (if it is the first contig read) or much higher.

**Comment by mkesapra** [comment]
Thank you for making it clear! I think this helps.
