### ISSUE TITLE
Spots - way to get the flanking genes?

### ISSUE THREAD

**Issue by gbouras13** [labgem/PPanGGOLiN#94]
Hi,

Thanks for creating PPanGGOLiN - I'm finding it to be a great way to see what is going on in the pangenome especially in terms of MGEs and prophages with the rgp analysis.

I have a question about spots of insertion. Is there any way to get the flanking genes that are common for a certain spot? I can see them when I draw the spot etc, but it would be great to get this information linked to each spot automatically if possible.

George

**Comment by axbazin** [comment]
Hi,

I recall writing code to do exactly this, but it does not look like it ended up in PPanGGOLiN itself as I can't find any option related to borders or flanking genes in the doc.
This information is computed within PPanGGOLiN at some point though, so it should be very strainghtforward to add.

I can probably add an option to do this at some point next week or so, I'll keep you updated.

Adelme

**Comment by axbazin** [comment]
Hi,

Well after some digging, it turns out that I did write the code to do that and added it to PPanGGOLiN some times ago, but it seems that I forgot to write the documentation about it.

The option --borders will write what I think you are looking for, to be used as such:

`ppanggolin write -p pangenome.h5 --borders --output OUTPUTDIR`

This will write a file called 'spot_borders.tsv', which has 4 columns:
1. the spot identifier
2. the number of RGP within this spot that have this border exactly
3. Comma-separated list of gene families of the 1st border
4. Comma-separated list of gene families of the 2nd border 

The fact that a border is 1st or 2nd is meaningless.
I hope this helps ! I'll update the doc as well.

Adelme

**Comment by gbouras13** [comment]
Adelme this is exactly what I am after, thanks so much!

George
