### ISSUE TITLE
How to extract the genome location of the spots

### ISSUE THREAD

**Issue by bioinformagica** [labgem/PPanGGOLiN#99]
Dear developers, is there any way to extract the genomes coordinates from the spots in the genomes ?

I'm trying to identify recombination hotspots in my pangenome reference strain. In this way I need to identify in this genome the location of the spots that have RGPs inside them and those that are empty. Doing this for spots that present RGPs is easy, as the output files present the coordinates of the RGPs. But doing this for empty spots is a little more complicated. The spot_borders.tsv file displays the ID and the 6 genes that make up the spots but not the coordinates of where in the genome these regions are located. I know it's easy to identify the location of these genes by crossing the annotation data with the clustering data, but I can't always identify the two edges of every spot. For all the empty spots I tried to find in my reference genome a region where at least one of the combinations (border1 + border2) is present, sometimes I managed to find it but most of the time I can only find one of the borders.

For example:

spot_id | number | border1 | border2
------------|-----------|-------------|----------|
7|15353|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|28|DKKAFEMC_00090,CHJOFNBH_03903,KEHGFKPA_02925|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808
7|9|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808|FIAOAHNM_00090,CHJOFNBH_03903,KEHGFKPA_02925
7|12|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|JOGCDNJL_01632,FMBJLEFL_01780,FMBJLEFL_01780
7|64|JOGCDNJL_01632,FMBJLEFL_01780,CAJPFCLC_02202|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|4|CHJOFNBH_03903,KEHGFKPA_02925,LBBFBCKB_03328|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808
7|1|JOGCDNJL_01632,JOGCDNJL_01632,FMBJLEFL_01780|FIAOAHNM_00090,DKKAFEMC_00090,DKKAFEMC_00090
7|1|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|JOGCDNJL_01632,FMBJLEFL_01780,IDEIKDGN_01283
7|36|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|JOGCDNJL_01632,FMBJLEFL_01780,OGPBNKPL_01645
7|14|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|JOGCDNJL_01632,JOGCDNJL_01632,FMBJLEFL_01780
7|1|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|FMBJLEFL_01780,PGBGKBCO_03808,DJDFLOED_02262
7|3|PGBGKBCO_03808,DJDFLOED_02262,CAJPFCLC_02202|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|2|JOGCDNJL_01632,FMBJLEFL_01780,CAJPFCLC_02202|DKKAFEMC_00090,CHJOFNBH_03903,KEHGFKPA_02925
7|1|JOGCDNJL_01632,FMBJLEFL_01780,FMBJLEFL_01780|DKKAFEMC_00090,CHJOFNBH_03903,KEHGFKPA_02925
7|1|JOGCDNJL_01632,FMBJLEFL_01780,FMBJLEFL_01780|DKKAFEMC_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|1|DKKAFEMC_00090,CHJOFNBH_03903,KEHGFKPA_02925|FMBJLEFL_01780,PGBGKBCO_03808,DJDFLOED_02262
7|1|FIAOAHNM_00090,CHJOFNBH_03903,KEHGFKPA_02925|FMBJLEFL_01780,PGBGKBCO_03808,DJDFLOED_02262
7|1|FMBJLEFL_01780,CAJPFCLC_02202,PIFHEODI_04173|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|2|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808|KEHGFKPA_02925,LBBFBCKB_03328,HBDDAOCK_01915
7|1|CHJOFNBH_03903,KEHGFKPA_02925,LBBFBCKB_03328|FMBJLEFL_01780,PGBGKBCO_03808,DJDFLOED_02262
7|1|JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808|FIAOAHNM_00090,DKKAFEMC_00090,KAJLLPMC_01779
7|1|JOGCDNJL_01632,JOGCDNJL_01632,FMBJLEFL_01780|DKKAFEMC_00090,CHJOFNBH_03903,KEHGFKPA_02925
7|1|PGBGKBCO_03808,DJDFLOED_02262,CAJPFCLC_02202|FIAOAHNM_00090,DKKAFEMC_00090,KEHGFKPA_02925
7|1|JOGCDNJL_01632,FMBJLEFL_01780,DJDFLOED_02262|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903
7|1|FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903|JOGCDNJL_01632,FMBJLEFL_01780,AKHIBPPD_01090

I did find a region on my ref genome that has the following sequence of genes:
```bash
JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808,DJDFLOED_02262,CAJPFCLC_02202,PIFHEODI_04173
```
The first 3 genes `JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808` do appear on the table in order but the other 3 `DJDFLOED_02262,CAJPFCLC_02202,PIFHEODI_04173` don't. I thought they might be showing up in different combinations, but there is no combination in the table that shows these genes in sequence.

Is there an easier way to do this?

Maybe I'm misunderstanding the concept of spot/RGP, are these assumptions true?

1. The RGPs are flanked by the 6 spot border genes (3 on each side);
2. All RGPs are inside of a spot, but a spot could be empty on a given genome;
3. Every genome on the pangenome has all or the majority of the spots.

**Comment by axbazin** [comment]
Hi,

There is no very easy way of doing what you wish, I think, which is if I understood correctly finding genomes where borders defining a spot are both present, but there are no RGP between those two borders. (equivalent to how Oliveira, Touchon, et.al. 2017 detected empty spots, I assume?) 

For your questions:
1. All RGPs that are assigned to spots are flanked by the 6 spot border genes, 3 on each side, but not all RGPs are assigned to spots (sometimes they are on contig borders, or fully cover a contig e.g. where the RGP is actually a plasmid)
2. Not all RGPs are inside of a spot. As said in 1., if they are not bordering 3 persistent genes on each side they are not assigned a spot.
3. No, I wouldn't say that's true even if you consider that a spot if there when empty, but some spots are found in most genomes.
As spots are defined by two set of genes that have a given order, if those two sets of genes are not close together when there is no RGP in between them, then the spot is not there. If the two sets are close together when there is no RGP, then I'd assume it's empty. But I've observed cases where, in some genomes, you see two borders close together and in some other genome of the same species they are very far appart and separated not only by RGPs but by other persistent genes as well. Since borders are defined using persistent genes, those genes should however be present in the majority of genomes.

You can indeed assume that the spots that have been defined by the RGPs in some genomes can be empty in other genomes, as long as the 2 borders defining the spots are still in close vicinity.

In the table that you show, it lists all the borders for the spot 7. Borders can varry between the different genomes, but those have been linked and assumed to be the same spot because they are very similar in terms of gene content, i.e. the order of genes and the genes themselves are partially conserved between borders.
The most common border by far in your example (and by experience there is often a single 'most common border', though I've seen(rare) cases where it was not the case) is JOGCDNJL_01632,FMBJLEFL_01780,PGBGKBCO_03808 on one side, and FIAOAHNM_00090,DKKAFEMC_00090,CHJOFNBH_03903 on the other side.

If my understanding of what you want to do is correct, I believe your approach should be good, but there are some things that maybe could make you miss the 2nd border in your attempts:
1. listed genes are ordered by their closeness to the RGP. So the order of one of the borders is inverted in terms of strandedness. The reason for this is because, the proper leading strand is not always well identified when working with illumina-based assemblies, so to properly find the spots between different genomes you need to ignore strandedness and only look at their relative order. (e.g. for 3 genes ABC, the gene sets A,B,C and C,B,A is the same thing)
2. In the genomes themselves, there can be occasionnally interlevead genes between border genes. this is because border genes are required to be persistent, and sometimes there are small genes between those persistent genes. So you can find border genes with the proper order but there can be an additional gene in between two of them sometimes.

Hopefully that helps and was clear, but if you feel like something is unclear, don't hesitate to ask !

Adelme

**Comment by bioinformagica** [comment]
Hello thanks for the quick and detailed replay !

> There is no very easy way of doing what you wish, I think, which is if I understood correctly finding genomes where borders defining a spot are both present, but there are no RGP between those two borders. (equivalent to how Oliveira, Touchon, et.al. 2017 detected empty spots, I assume?)

Yeah that is precisely what i want to accomplish.

Thanks a lot i have a very good grasp of this concepts now !
